### ISSUE TITLE
Content removed from Resources Page

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Psychology#2]
The following items are intranet and do not belong on the resources page catered to prospective students. Suggestions can be made to the program as to where this should be housed outside of the website. 

[MisplacedPsychologyResources (1).docx](https://github.com/TULiberalArts/Psychology/files/1072637/MisplacedPsychologyResources.1.docx)

@saracurnow when you get to this site, please see the note about the content that needs to be re-written on the Resources page.

**Comment by saracurnow** [comment]
Will do! Thanks for alerting me.

**Comment by CVE82** [comment]
Thanks a million! Just trying to make notes as I am working on programs and sidebars so I don't forget anything =)
