### ISSUE TITLE
Please Center Hero Image

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Psychology#7]
Hey Zac Attack! Whenever you get a chance can you please center the hero image a bit so the geometric brains are a little more visible and centered? Thanks so much!

**Comment by ZMcGroarty** [comment]
![psychology-min](https://user-images.githubusercontent.com/15017242/36167070-920bd5c0-10c2-11e8-9d4f-c66fe335908a.png)

**Comment by CVE82** [comment]
Thank you!
